name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin docker.io
        for i in ./services/*; \
        do docker build . --file $i/Dockerfile --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/micro-portfolio-$(basename $i):latest --tag docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/micro-portfolio-$(basename $i):$GITHUB_SHA && \
        docker push --all-tags docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/micro-portfolio-$(basename $i); \
        done
